import { z } from "zod";

// ─── Source Classification ────────────────────────────────────────────────────
// Every piece of content in the system must carry these metadata fields.
// This is non-negotiable: mixing official and homebrew without metadata
// destroys the reliability of any rule query.

export const SourceTypeSchema = z.enum([
  "official",         // D&D 2024 core books
  "srd",             // Systems Reference Document
  "campaign",        // Campaign-specific canon
  "homebrew_external", // Third-party homebrew (e.g., published modules)
  "homebrew_user",   // User-created homebrew
  "ai_inferred",     // Generated by AI — lowest trust
]);
export type SourceType = z.infer<typeof SourceTypeSchema>;

export const AuthorityLevelSchema = z.enum(["high", "medium", "low"]);
export type AuthorityLevel = z.infer<typeof AuthorityLevelSchema>;

// ─── Entity Types (used in changelog and issues) ──────────────────────────────
export const EntityTypeSchema = z.enum([
  "campaign",
  "session",
  "npc",
  "player",
  "location",
  "faction",
  "document",
  "encounter",
  "rule_source",
  "campaign_rule",
  "llm_config",
  "relation",
]);
export type EntityType = z.infer<typeof EntityTypeSchema>;

// ─── Author Types ─────────────────────────────────────────────────────────────
export const AuthorTypeSchema = z.enum(["user", "ai", "system"]);
export type AuthorType = z.infer<typeof AuthorTypeSchema>;

// ─── Issue Types & Severity ───────────────────────────────────────────────────
export const IssueTypeSchema = z.enum([
  "rules_conflict",
  "narrative_inconsistency",
  "duplicate_entity",
  "unbalanced_encounter",
  "broken_reference",
  "data_inconsistency",
]);
export type IssueType = z.infer<typeof IssueTypeSchema>;

export const IssueSeveritySchema = z.enum(["critical", "major", "minor", "info"]);
export type IssueSeverity = z.infer<typeof IssueSeveritySchema>;

export const IssueStatusSchema = z.enum(["open", "in_progress", "resolved", "dismissed"]);
export type IssueStatus = z.infer<typeof IssueStatusSchema>;

// ─── Campaign Status ──────────────────────────────────────────────────────────
export const CampaignStatusSchema = z.enum(["active", "paused", "completed", "archived"]);
export type CampaignStatus = z.infer<typeof CampaignStatusSchema>;

// ─── NPC Status ───────────────────────────────────────────────────────────────
export const NpcStatusSchema = z.enum(["alive", "dead", "unknown", "missing"]);
export type NpcStatus = z.infer<typeof NpcStatusSchema>;

// ─── NPC Disposition ─────────────────────────────────────────────────────────
export const NpcDispositionSchema = z.enum(["ally", "neutral", "enemy"]);
export type NpcDisposition = z.infer<typeof NpcDispositionSchema>;

// ─── Document Content Types ───────────────────────────────────────────────────
export const ContentTypeSchema = z.enum(["markdown", "plaintext", "pdf"]);
export type ContentType = z.infer<typeof ContentTypeSchema>;
