import { z } from "zod";

// ─── Source Classification ────────────────────────────────────────────────────
// Every piece of content in the system must carry these metadata fields.
// This is non-negotiable: mixing official and homebrew without metadata
// destroys the reliability of any rule query.

export const SourceTypeSchema = z.enum([
  "official",         // D&D 2024 core books
  "srd",             // Systems Reference Document
  "campaign",        // Campaign-specific canon
  "homebrew_external", // Third-party homebrew (e.g., published modules)
  "homebrew_user",   // User-created homebrew
  "ai_inferred",     // Generated by AI — lowest trust
]);
export type SourceType = z.infer<typeof SourceTypeSchema>;

export const AuthorityLevelSchema = z.enum(["high", "medium", "low"]);
export type AuthorityLevel = z.infer<typeof AuthorityLevelSchema>;

export const AUTHORITY_MAP: Record<SourceType, AuthorityLevel> = {
  official: "high",
  srd: "high",
  campaign: "medium",
  homebrew_external: "medium",
  homebrew_user: "low",
  ai_inferred: "low",
};

export const SourceMetaSchema = z.object({
  sourceType: SourceTypeSchema,
  authorityLevel: AuthorityLevelSchema,
  version: z.string().optional(),
  campaignId: z.string().optional(),
});
export type SourceMeta = z.infer<typeof SourceMetaSchema>;

// ─── Entity Types (used in changelog and issues) ──────────────────────────────
export const EntityTypeSchema = z.enum([
  "campaign",
  "session",
  "npc",
  "location",
  "faction",
  "document",
  "rule_source",
  "campaign_rule",
  "llm_config",
  "relation",
]);
export type EntityType = z.infer<typeof EntityTypeSchema>;

// ─── Author Types ─────────────────────────────────────────────────────────────
export const AuthorTypeSchema = z.enum(["user", "ai", "system"]);
export type AuthorType = z.infer<typeof AuthorTypeSchema>;

// ─── Issue Types & Severity ───────────────────────────────────────────────────
export const IssueTypeSchema = z.enum([
  "rules_conflict",
  "narrative_inconsistency",
  "duplicate_entity",
  "unbalanced_encounter",
  "broken_reference",
  "data_inconsistency",
]);
export type IssueType = z.infer<typeof IssueTypeSchema>;

export const IssueSeveritySchema = z.enum(["critical", "major", "minor", "info"]);
export type IssueSeverity = z.infer<typeof IssueSeveritySchema>;

export const IssueStatusSchema = z.enum(["open", "in_progress", "resolved", "dismissed"]);
export type IssueStatus = z.infer<typeof IssueStatusSchema>;

// ─── Campaign Status ──────────────────────────────────────────────────────────
export const CampaignStatusSchema = z.enum(["active", "paused", "completed", "archived"]);
export type CampaignStatus = z.infer<typeof CampaignStatusSchema>;

// ─── NPC Status ───────────────────────────────────────────────────────────────
export const NpcStatusSchema = z.enum(["alive", "dead", "unknown", "missing"]);
export type NpcStatus = z.infer<typeof NpcStatusSchema>;

// ─── Document Content Types ───────────────────────────────────────────────────
export const ContentTypeSchema = z.enum(["markdown", "plaintext", "pdf"]);
export type ContentType = z.infer<typeof ContentTypeSchema>;

// ─── API Response Envelope ────────────────────────────────────────────────────
export const ApiSuccessSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>
  z.object({
    success: z.literal(true),
    data: dataSchema,
  });

export const ApiErrorSchema = z.object({
  success: z.literal(false),
  error: z.object({
    code: z.string(),
    message: z.string(),
    details: z.unknown().optional(),
  }),
});

export type ApiError = z.infer<typeof ApiErrorSchema>;

// ─── Pagination ───────────────────────────────────────────────────────────────
export const PaginationQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
});
export type PaginationQuery = z.infer<typeof PaginationQuerySchema>;

export const PaginatedResponseSchema = <T extends z.ZodTypeAny>(itemSchema: T) =>
  z.object({
    items: z.array(itemSchema),
    total: z.number(),
    page: z.number(),
    limit: z.number(),
    hasNext: z.boolean(),
  });
